// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, lines_longer_than_80_chars, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqKvoMx6gWbSFHdDG-zYgguTDjtAWWnk',
    appId: '1:919442709959:android:c7285f09cca745d5d80de2',
    messagingSenderId: '919442709959',
    projectId: 'tarifdefteriuygulamasi',
    storageBucket: 'tarifdefteriuygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eOKgm2mvBXn6vk0qS9PgYNE9HYoDtt8',
    appId: '1:919442709959:ios:856cc993d496795dd80de2',
    messagingSenderId: '919442709959',
    projectId: 'tarifdefteriuygulamasi',
    storageBucket: 'tarifdefteriuygulamasi.firebasestorage.app',
    iosBundleId: 'com.sudekaazan.tarifDefteriYeni',
  );
}
